name: iOS Tests
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPR_USER: ${{ secrets.GITHUB_ACTOR }}

jobs:
  android-tests:
    timeout-minutes: 45
    name: iOS Tests
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v5

      - name: Select Xcode 26.1
        run: sudo xcode-select -s /Applications/Xcode_26.1.app/Contents/Developer

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          cd ./example
          yarn install --frozen-lockfile

      - name: Create build
        run: |
          cd ./example
          yarn e2e:ios:build
