name: iOS Tests
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPR_USER: ${{ secrets.GITHUB_ACTOR }}

jobs:
  android-tests:
    timeout-minutes: 45
    name: iOS Tests
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v5

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.0.1"

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          cd ./example
          yarn install --frozen-lockfile

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Create build
        run: |
          cd ./example

          yarn e2e:ios:build

          xcodebuild \
            -workspace ios/xmtpreactnativesdkexample.xcworkspace  \
            -scheme xmtpreactnativesdkexample  \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath ios/build \
            build

          xcrun simctl boot "iPhone 17"

          BUNDLE_ID=$(/usr/libexec/PlistBuddy -c "Print:CFBundleIdentifier" "$APP_PATH/Info.plist")
          xcrun simctl install "iPhone 17" ios/build/Products/xmtpreactnativesdkexample.app

          yarn e2e:android:all
